version: '3'
services:
  proxy:
    image: dockerspring
    container_name: appspring
    build:
      context: .
    #volumes:
    #  - .\site:/usr/share/nginx/htm
    #volumes:
    #  - site:/usr/share/nginx/htm
    ports:
      - "8000:80"
    networks:
      - appspringeth

networks:
  appspringeth:
    driver: bridge

    #volumes:
    #  site:

    # docker-compose up -d